# Generated by Django 4.0.4 on 2022-04-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='admin',
            field=models.CharField(help_text='Username of the user that created this FORUM', max_length=25),
        ),
    ]
