# Generated by Django 4.0.4 on 2022-04-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(help_text='User Bio', null=True),
        ),
    ]
